---
  - hosts: all
    vars:
      ansible_python_interpreter: "/usr/bin/python3"
    user: ubuntu
    gather_facts: yes

    tasks:
    - shell:
        cmd: |
          apt-get update
          apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
          apt-get update && apt-get install -y docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')
      become: yes
      register: dockerInstall
    - debug: msg="{{ dockerInstall.stdout }}"

    - shell:
        cmd: |
          usermod -aG docker ubuntu
      become: yes
      register: userMod
    - debug: msg="{{ userMod.stdout }}"

    - shell:
        cmd: |
          cat << EOF > /etc/docker/daemon.json
          {
          "exec-opts": ["native.cgroupdriver=systemd"]
          }
          EOF
      become: yes
      register: cgroupAdd
    - debug: msg="{{ cgroupAdd.stdout }}"
