---
  - hosts: all
    vars:
      ansible_python_interpreter: "/usr/bin/python3"
    user: ubuntu
    gather_facts: yes

    tasks:
    - shell:
        cmd: |
          apt-get update && apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
          cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
          deb http://apt.kubernetes.io/ kubernetes-xenial main
          EOF
          apt-get update
          apt-get install -y kubelet kubeadm kubectl
      become: yes
      register: kubernetesInstall
    - debug: msg="{{ kubernetesInstall.stdout }}"

    - shell:
        cmd: |
          swapoff -a
      become: yes
      register: disableSwap
    - debug: msg="{{ disableSwap.stdout }}"
